title: Kristel Fung
author: Kristel Fung
email: kristelfung@gmail.com
description: > # this means to ignore newlines after this
  Kristel's website! Portfolio containing my resume, projects, and a semi-active blog.

# social links
github_username: kristelfung
linkedin_username: kristelfung
behance_username: kristelfung

sass:
    style: compressed # we want our css minified

# compress our html
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

# Jekyll
permalink: /blog/:title/
include: [_redirects]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'LICENSE.txt', 'bullet-journal.gemspec', 'TODO']
collections: 
  projects:
    output: true
  skills:
    output: true