title: Kristel Fung
author: Kristel Fung
email: kristelfung@gmail.com
description: > # this means to ignore newlines after this
  Kristel's website!

# social links
github_username:  kristelfung
linkedin_username: kristel-fung-4ba37635

sass:
    style: compressed # we want our css minified

# compress our html
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

# Jekyll
permalink: /blog/:title/
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'LICENSE.txt', 'bullet-journal.gemspec', 'TODO']
collections: 
  projects:
    output: true
  skills:
    output: true