title: Kristel Fung
author: GitHub User
email: kristelfung@gmail.com
description: > # this means to ignore newlines after this
  Portfolio of Kristel Fung.

# social links
github_username:  kristelfung
linkedin_username: kristelfung

sass:
    style: compressed # we want our css minified

# compress our html
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

# Jekyll
permalink: /blog/:title/
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'LICENSE.txt', 'bullet-journal.gemspec']
collections: 
  projects:
    output: true